logging:
  # style: '{'
  level: DEBUG
  filename: ranga.log
  format: '%(asctime)s-%(process)d-%(levelname)s-%(message)s'
  datefmt: '%d-%b-%y %H:%M:%S'
env:
  - name: RANGA_DATA
    default: $HOME/.ranga
  - name: RANGA_DB
    default: $HOME/.ranga/index.db
  - name: RANGA_PORT
    default: 8000
