logging:
  # style: '{'
  level: DEBUG
  filename: ffindex.log
  format: '%(asctime)s-%(process)d-%(levelname)s-%(message)s'
  datefmt: '%d-%b-%y %H:%M:%S'
env:
  - name: FFINDEX_DB
    default: $HOME/.ffindex.db
  - name: FFINDEX_PORT
    default: 8000
